frase = str(input('Digite uma frase qualquer: '))
frase = frase.upper().strip()
print('A letra \'a\' aparece {} veze(s)'.format(frase.count('A')))
print('Ela aparece a primeira vez na posição: {}'.format(frase.find('A')+1))
print('Ela aparece a última vez na posição: {}'.format(frase.rfind('A')+1))